In [15]:
import numpy as np
import pandas as pd

In [8]:
ls data/

data_cleaned_1st(2).xlsx                          spray.csv
mapdata_copyright_openstreetmap_contributors.rds  test.csv
mapdata_copyright_openstreetmap_contributors.txt  train.csv
noaa_weather_qclcd_documentation.pdf              weather.csv
sampleSubmission.csv                              west_nile/

Id: the id of the record
Date: date that the WNV test is performed
Address: approximate address of the location of trap. This is used to send to the GeoCoder. 
Species: the species of mosquitos
Block: block number of address
Street: street name
Trap: Id of the trap
AddressNumberAndStreet: approximate address returned from GeoCoder
Latitude, Longitude: Latitude and Longitude returned from GeoCoder
AddressAccuracy: accuracy returned from GeoCoder
NumMosquitos: number of mosquitoes caught in this trap
WnvPresent: whether West Nile Virus was present in these mosquitos. 1 means WNV is present, and 0 means not present.

In [33]:
name=['Date','Address','Species','Block','Street','Trap','AddressNumberAndStreet','Latitue','AddressAccuracy','NumMosquitos','WnvPresent']

In [65]:
train_set=pd.read_csv('data/train.csv',header=0)
validation_set=pd.read_csv('data/validation.csv',header=0)
weather=pd.read_csv('data/weather.csv',header=0)

In [66]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10506 entries, 0 to 10505
Data columns (total 12 columns):
Date                      10506 non-null object
Address                   10506 non-null object
Species                   10506 non-null object
Block                     10506 non-null int64
Street                    10506 non-null object
Trap                      10506 non-null object
AddressNumberAndStreet    10506 non-null object
Latitude                  10506 non-null float64
Longitude                 10506 non-null float64
AddressAccuracy           10506 non-null int64
NumMosquitos              10506 non-null int64
WnvPresent                10506 non-null int64
dtypes: float64(2), int64(4), object(6)
memory usage: 985.0+ KB

In [67]:
validation_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55883 entries, 0 to 55882
Data columns (total 11 columns):
Id                        55883 non-null int64
Date                      55883 non-null object
Address                   55883 non-null object
Species                   55883 non-null object
Block                     55883 non-null int64
Street                    55883 non-null object
Trap                      55883 non-null object
AddressNumberAndStreet    55883 non-null object
Latitude                  55883 non-null float64
Longitude                 55883 non-null float64
AddressAccuracy           55883 non-null int64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.7+ MB

In [89]:
combined_set = pd.concat([train_set, validation_set], axis = 0)
combined_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 66389 entries, 0 to 55882
Data columns (total 13 columns):
Address                   66389 non-null object
AddressAccuracy           66389 non-null int64
AddressNumberAndStreet    66389 non-null object
Block                     66389 non-null int64
Date                      66389 non-null object
Id                        55883 non-null float64
Latitude                  66389 non-null float64
Longitude                 66389 non-null float64
NumMosquitos              10506 non-null float64
Species                   66389 non-null object
Street                    66389 non-null object
Trap                      66389 non-null object
WnvPresent                10506 non-null float64
dtypes: float64(5), int64(2), object(6)
memory usage: 7.1+ MB

In [82]:
combined_set=combined_set['Species']

In [84]:
combined_set

0        CULEX PIPIENS/RESTUANS
1                CULEX RESTUANS
2                CULEX RESTUANS
3        CULEX PIPIENS/RESTUANS
4                CULEX RESTUANS
5                CULEX RESTUANS
6                CULEX RESTUANS
7        CULEX PIPIENS/RESTUANS
8                CULEX RESTUANS
9                CULEX RESTUANS
10       CULEX PIPIENS/RESTUANS
11       CULEX PIPIENS/RESTUANS
12               CULEX RESTUANS
13       CULEX PIPIENS/RESTUANS
14               CULEX RESTUANS
15               CULEX RESTUANS
16               CULEX RESTUANS
17               CULEX RESTUANS
18                CULEX PIPIENS
19       CULEX PIPIENS/RESTUANS
20               CULEX RESTUANS
21       CULEX PIPIENS/RESTUANS
22       CULEX PIPIENS/RESTUANS
23               CULEX RESTUANS
24               CULEX RESTUANS
25       CULEX PIPIENS/RESTUANS
26               CULEX RESTUANS
27                CULEX PIPIENS
28       CULEX PIPIENS/RESTUANS
29               CULEX RESTUANS
                  ...
55853             CULEX PIPIENS
55854          CULEX SALINARIUS
55855           CULEX TERRITANS
55856            CULEX TARSALIS
55857         UNSPECIFIED CULEX
55858           CULEX ERRATICUS
55859    CULEX PIPIENS/RESTUANS
55860            CULEX RESTUANS
55861             CULEX PIPIENS
55862          CULEX SALINARIUS
55863           CULEX TERRITANS
55864            CULEX TARSALIS
55865         UNSPECIFIED CULEX
55866           CULEX ERRATICUS
55867    CULEX PIPIENS/RESTUANS
55868            CULEX RESTUANS
55869             CULEX PIPIENS
55870          CULEX SALINARIUS
55871           CULEX TERRITANS
55872            CULEX TARSALIS
55873         UNSPECIFIED CULEX
55874           CULEX ERRATICUS
55875    CULEX PIPIENS/RESTUANS
55876            CULEX RESTUANS
55877             CULEX PIPIENS
55878          CULEX SALINARIUS
55879           CULEX TERRITANS
55880            CULEX TARSALIS
55881         UNSPECIFIED CULEX
55882           CULEX ERRATICUS
Name: Species, Length: 66389, dtype: object

In [86]:
combined_set['Species']=pd.Categorical(combined_set['Species']).codes

In [90]:
test=pd.get_dummies(combined_set,prefix=['Species'])

ValueError: Length of 'prefix' (1) did not match the length of the columns being encoded (6).

In [87]:
combined_set

,Address,AddressAccuracy,AddressNumberAndStreet,Block,Date,Id,Latitude,Longitude,NumMosquitos,Species,Street,Trap,WnvPresent
0,"4100 North Oak Park Avenue, Chicago, IL 60634,...",9,"4100 N OAK PARK AVE, Chicago, IL",41,2007-05-29,NaN,41.954690,-87.800991,1.0,2,N OAK PARK AVE,T002,0.0
1,"4100 North Oak Park Avenue, Chicago, IL 60634,...",9,"4100 N OAK PARK AVE, Chicago, IL",41,2007-05-29,NaN,41.954690,-87.800991,1.0,3,N OAK PARK AVE,T002,0.0
2,"6200 North Mandell Avenue, Chicago, IL 60646, USA",9,"6200 N MANDELL AVE, Chicago, IL",62,2007-05-29,NaN,41.994991,-87.769279,1.0,3,N MANDELL AVE,T007,0.0
3,"7900 West Foster Avenue, Chicago, IL 60656, USA",8,"7900 W FOSTER AVE, Chicago, IL",79,2007-05-29,NaN,41.974089,-87.824812,1.0,2,W FOSTER AVE,T015,0.0
4,"7900 West Foster Avenue, Chicago, IL 60656, USA",8,"7900 W FOSTER AVE, Chicago, IL",79,2007-05-29,NaN,41.974089,-87.824812,4.0,3,W FOSTER AVE,T015,0.0
5,"1500 West Webster Avenue, Chicago, IL 60614, USA",8,"1500 W WEBSTER AVE, Chicago, IL",15,2007-05-29,NaN,41.921600,-87.666455,2.0,3,W WEBSTER AVE,T045,0.0
6,"2500 West Grand Avenue, Chicago, IL 60654, USA",8,"2500 W GRAND AVE, Chicago, IL",25,2007-05-29,NaN,41.891118,-87.654491,1.0,3,W GRAND AVE,T046,0.0
7,"1100 Roosevelt Road, Chicago, IL 60608, USA",8,"1100 W ROOSEVELT, Chicago, IL",11,2007-05-29,NaN,41.867108,-87.654224,1.0,2,W ROOSEVELT,T048,0.0
8,"1100 Roosevelt Road, Chicago, IL 60608, USA",8,"1100 W ROOSEVELT, Chicago, IL",11,2007-05-29,NaN,41.867108,-87.654224,2.0,3,W ROOSEVELT,T048,0.0
9,"1100 West Chicago Avenue, Chicago, IL 60642, USA",8,"1100 W CHICAGO, Chicago, IL",11,2007-05-29,NaN,41.896282,-87.655232,1.0,3,W CHICAGO,T049,0.0
10,"2100 North Stave Street, Chicago, IL 60647, USA",8,"2100 N STAVE ST, Chicago, IL",21,2007-05-29,NaN,41.919343,-87.694259,1.0,2,N STAVE ST,T050,0.0
11,"2200 North Cannon Drive, Chicago, IL 60614, USA",8,"2200 N CANNON DR, Chicago, IL",22,2007-05-29,NaN,41.921965,-87.632085,2.0,2,N CANNON DR,T054,0.0
12,"2200 North Cannon Drive, Chicago, IL 60614, USA",8,"2200 N CANNON DR, Chicago, IL",22,2007-05-29,NaN,41.921965,-87.632085,3.0,3,N CANNON DR,T054,0.0
13,"2200 West 113th Street, Chicago, IL 60643, USA",8,"2200 W 113TH ST, Chicago, IL",22,2007-05-29,NaN,41.688324,-87.676709,1.0,2,W 113TH ST,T086,0.0
14,"2200 West 113th Street, Chicago, IL 60643, USA",8,"2200 W 113TH ST, Chicago, IL",22,2007-05-29,NaN,41.688324,-87.676709,1.0,3,W 113TH ST,T086,0.0
15,"1100 South Peoria Street, Chicago, IL 60608, USA",8,"1100 S PEORIA ST, Chicago, IL",11,2007-05-29,NaN,41.862292,-87.648860,1.0,3,S PEORIA ST,T091,0.0
16,"1700 West 95th Street, Chicago, IL 60643, USA",9,"1700 W 95TH ST, Chicago, IL",17,2007-05-29,NaN,41.720848,-87.666014,3.0,3,W 95TH ST,T094,0.0
17,"2200 West 89th Street, Chicago, IL 60643, USA",8,"2200 W 89TH ST, Chicago, IL",22,2007-05-29,NaN,41.731922,-87.677512,5.0,3,W 89TH ST,T096,0.0
18,"2200 West 89th Street, Chicago, IL 60643, USA",8,"2200 W 89TH ST, Chicago, IL",22,2007-05-29,NaN,41.731922,-87.677512,1.0,1,W 89TH ST,T096,0.0
19,"North Streeter Drive, Chicago, IL 60611, USA",5,"5300 N STREETER DR, Chicago, IL",53,2007-05-29,NaN,41.891126,-87.611560,1.0,2,N STREETER DR,T129,0.0
20,"North Streeter Drive, Chicago, IL 60611, USA",5,"5300 N STREETER DR, Chicago, IL",53,2007-05-29,NaN,41.891126,-87.611560,2.0,3,N STREETER DR,T129,0.0
21,"6500 North Oak Park Avenue, Chicago, IL 60631,...",8,"6500 N OAK PARK AVE, Chicago, IL",65,2007-05-29,NaN,41.999129,-87.795585,1.0,2,N OAK PARK AVE,T143,0.0
22,"7500 North Oakley Avenue, Chicago, IL 60645, USA",8,"7500 N OAKLEY AVE, Chicago, IL",75,2007-05-29,NaN,42.017430,-87.687769,1.0,2,N OAKLEY AVE,T148,0.0
23,"1500 North Long Avenue, Chicago, IL 60651, USA",8,"1500 N LONG AVE, Chicago, IL",15,2007-05-29,NaN,41.907645,-87.760886,1.0,3,N LONG AVE,T153,0.0
24,"8900 South Carpenter Street, Chicago, IL 60620...",8,"8900 S CARPENTER ST, Chicago, IL",89,2007-05-29,NaN,41.732984,-87.649642,1.0,3,S CARPENTER ST,T159,0.0
25,"4100 North Oak Park Avenue, Chicago, IL 60634,...",9,"4100 N OAK PARK AVE, Chicago, IL",41,2007-06-05,NaN,41.954690,-87.800991,3.0,2,N OAK PARK AVE,T002,0.0
26,"4100 North Oak Park Avenue, Chicago, IL 60634,...",9,"4100 N OAK PARK AVE, Chicago, IL",41,2007-06-05,NaN,41.954690,-87.800991,5.0,3,N OAK PARK AVE,T002,0.0
27,"4100 North Oak Park Avenue, Chicago, IL 60634,...",9,"4100 N OAK PARK AVE, Chicago, IL",41,2007-06-05,NaN,41.954690,-87.800991,1.0,1,N OAK PARK AVE,T002,0.0
28,"7900 West Foster Avenue, Chicago, IL 60656, USA",8,"7900 W FOSTER AVE, Chicago, IL",79,2007-06-05,NaN,41.974089,-87.824812,1.0,2,W FOSTER AVE,T015,0.0
29,"7900 West Foster Avenue, Chicago, IL 60656, USA",8,"7900 W FOSTER AVE, Chicago, IL",79,2007-06-05,NaN,41.974089,-87.824812,2.0,3,W FOSTER AVE,T015,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55853,"3400 West 77th Street, Chicago, IL 60652, USA",8,"3400 W 77TH ST, Chicago, IL",34,10/2/2014,116264.0,41.753391,-87.707394,NaN,1,W 77TH ST,T238,NaN
55854,"3400 West 77th Street, Chicago, IL 60652, USA",8,"3400 W 77TH ST, Chicago, IL",34,10/2/2014,116265.0,41.753391,-87.707394,NaN,4,W 77TH ST,T238,NaN
55855,"3400 West 77th Street, Chicago, IL 60652, USA",8,"3400 W 77TH ST, Chicago, IL",34,10/2/2014,116266.0,41.753391,-87.707394,NaN,6,W 77TH ST,T238,NaN
55856,"3400 West 77th Street, Chicago, IL 60652, USA",8,"3400 W 77TH ST, Chicago, IL",34,10/2/2014,116267.0,41.753391,-87.707394,NaN,5,W 77TH ST,T238,NaN
55857,"3400 West 77th Street, Chicago, IL 60652, USA",8,"3400 W 77TH ST, Chicago, IL",34,10/2/2014,116268.0,41.753391,-87.707394,NaN,7,W 77TH ST,T238,NaN
55858,"3400 West 77th Street, Chicago, IL 60652, USA",8,"3400 W 77TH ST, Chicago, IL",34,10/2/2014,116269.0,41.753391,-87.707394,NaN,0,W 77TH ST,T238,NaN
55859,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116270.0,41.777689,-87.749149,NaN,2,W 63RD PL,T065A,NaN
55860,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116271.0,41.777689,-87.749149,NaN,3,W 63RD PL,T065A,NaN
55861,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116272.0,41.777689,-87.749149,NaN,1,W 63RD PL,T065A,NaN
55862,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116273.0,41.777689,-87.749149,NaN,4,W 63RD PL,T065A,NaN
55863,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116274.0,41.777689,-87.749149,NaN,6,W 63RD PL,T065A,NaN
55864,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116275.0,41.777689,-87.749149,NaN,5,W 63RD PL,T065A,NaN
55865,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116276.0,41.777689,-87.749149,NaN,7,W 63RD PL,T065A,NaN
55866,"5100 West 63rd Place, Chicago, IL 60638, USA",9,"5100 W 63RD PL, Chicago, IL",51,10/2/2014,116277.0,41.777689,-87.749149,NaN,0,W 63RD PL,T065A,NaN
55867,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116278.0,41.719140,-87.669539,NaN,2,S LONGWOOD DR,T094B,NaN
55868,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116279.0,41.719140,-87.669539,NaN,3,S LONGWOOD DR,T094B,NaN
55869,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116280.0,41.719140,-87.669539,NaN,1,S LONGWOOD DR,T094B,NaN
55870,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116281.0,41.719140,-87.669539,NaN,4,S LONGWOOD DR,T094B,NaN
55871,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116282.0,41.719140,-87.669539,NaN,6,S LONGWOOD DR,T094B,NaN
55872,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116283.0,41.719140,-87.669539,NaN,5,S LONGWOOD DR,T094B,NaN
55873,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116284.0,41.719140,-87.669539,NaN,7,S LONGWOOD DR,T094B,NaN
55874,"9600 South Longwood Drive, Chicago, IL 60643, USA",9,"9600 S LONGWOOD DR, Chicago, IL",96,10/2/2014,116285.0,41.719140,-87.669539,NaN,0,S LONGWOOD DR,T094B,NaN
55875,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116286.0,41.925652,-87.633590,NaN,2,N CANNON DR,T054C,NaN
55876,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116287.0,41.925652,-87.633590,NaN,3,N CANNON DR,T054C,NaN
55877,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116288.0,41.925652,-87.633590,NaN,1,N CANNON DR,T054C,NaN
55878,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116289.0,41.925652,-87.633590,NaN,4,N CANNON DR,T054C,NaN
55879,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116290.0,41.925652,-87.633590,NaN,6,N CANNON DR,T054C,NaN
55880,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116291.0,41.925652,-87.633590,NaN,5,N CANNON DR,T054C,NaN
55881,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116292.0,41.925652,-87.633590,NaN,7,N CANNON DR,T054C,NaN
55882,"2100 North Cannon Drive, Chicago, IL 60614, USA",8,"2100 N CANNON DR, Chicago, IL",21,10/2/2014,116293.0,41.925652,-87.633590,NaN,0,N CANNON DR,T054C,NaN

In [61]:
train_set_part=train_set[['Species']]
train_set_part['Species']=pd.Categorical(train_set_part['Species']).codes
train_set_part

/opt/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

       Species
0            2
1            3
2            3
3            2
4            3
5            3
6            3
7            2
8            3
9            3
10           2
11           2
12           3
13           2
14           3
15           3
16           3
17           3
18           1
19           2
20           3
21           2
22           2
23           3
24           3
25           2
26           3
27           1
28           2
29           3
...        ...
10476        2
10477        3
10478        1
10479        1
10480        2
10481        3
10482        1
10483        3
10484        2
10485        2
10486        1
10487        1
10488        1
10489        1
10490        2
10491        2
10492        1
10493        2
10494        2
10495        1
10496        2
10497        2
10498        2
10499        1
10500        2
10501        2
10502        2
10503        2
10504        2
10505        2

[10506 rows x 1 columns]